baseURL: 'https://anlor.top' # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: '安洛的主页'
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Contact
          url: contact/
          weight: 30
      #  - name: Articles
        #  url: articles/
        #  weight: 20
        - name: Projects
          url: projects
          weight: 15

     # - name: Categories
        #   url: categories/
        #   weight: 10
        # - name: new Tab
        #   url: mewtab/
        #   weight: defines order of tabs
   


params:
    author: Anlor


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: 安洛(Anlor)
        description: |

          Hello, I am Anlor, a computer science student. 
        

          This is my home page.
        imageUrl: "/images/profile.webp"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Drive
              url: https://alspace.anlor.top/
            - name: Blog
              url: https://blog.anlor.top/
    # mainSections:
      # - articles

    socialIcons:
        - name: github
          url: "https://github.com/chenxiex"
        - name: email
          url: "mailto://anlor@anlor.top"
        - name: zhihu
          url: "https://www.zhihu.com/people/qi-dian-47-70"
        - name: luogu
          url: "https://www.luogu.com.cn/user/76185"
      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          #favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/favicon-128x128.png"
          safari_pinned_tab: "/images/favicon-128x128.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

