#!/bin/sh
USER=developer
HOST=20.222.235.16
DIR=alhome   # the directory where your web site files should go

hugo && rsync -avz --delete public/ ${USER}@${HOST}:~/${DIR} # this will delete everything on the server that's not in the local public folder 

exit 0
